### ISSUE TITLE
Provide Repository description

### ISSUE THREAD

**Issue by dennlinger** [heyjing/SRLScore#1]
Since I cannot modify the description myself, it would be great if you can adjust the description (appearing in the top right of the repository, as well as when searching for it).
In my mind, we could add something like

"An SRL-based approach to factuality estimation [for text summarization]", where the part in [] is optional.

Thanks in advance!

**Comment by heyjing** [comment]
Sorry, I have just saw the Email-Notifications about these issues, since the email-address bound with my Github Account is not my default email address and I seldom checked it.. But now description added!

**Comment by dennlinger** [comment]
Perfect, thanks! Also great tags added as well!
